[package]
name = "monkey-rs"
version = "0.1.0"
edition = "2021"
authors = ["Yago Iglesias"]


[workspace]
members = ["crates/*"]


[dependencies]
# local crates
lexer = { path = "./crates/lexer" }
parser = { path = "./crates/parser" }
interpreter = { path = "./crates/interpreter" }
compiler = { path = "./crates/compiler" }
vm = { path = "./crates/vm" }
repl = { path = "./crates/repl" }
