name: Rust

on:
  push:
    branches: ["master"]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --all --verbose --release
      - name: Run tests
        run: cargo test --all --verbose --release
      - name: Lint
        run: ./run_linter.sh
